version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - frontend
      - backend
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    networks:
      - backend
volumes:
  pgdata:
networks:
  frontend:
  backend:    
    
    
