version: "3.8"

services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - app-data:/usr/share/nginx/html
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  app-data:
  db-data:
